name: "Deploy InMemoryQueue to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH_Base: 'MemoryQueue.Base/MemoryQueue.Base.csproj'

  PROJECT_PATH_Server_GRPC: 'MemoryQueue.GRPC/MemoryQueue.GRPC.csproj'
  PROJECT_PATH_Client_GRPC: 'MemoryQueue.Client.Grpc/MemoryQueue.Client.Grpc.csproj'

  PROJECT_PATH_Server_SignalR: 'MemoryQueue.SignalR/MemoryQueue.SignalR.csproj'
  PROJECT_PATH_Client_SignalR: 'MemoryQueue.Client.SignalR/MemoryQueue.Client.SignalR.csproj'

  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Restore packages InMemoryQueue Base'
      run: dotnet restore ${{ env.PROJECT_PATH_Base }}

    - name: 'Build project InMemoryQueue Base'
      run: dotnet build ${{ env.PROJECT_PATH_Base }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Restore packages InMemoryQueue Server GRPC'
      run: dotnet restore ${{ env.PROJECT_PATH_Server_GRPC }}

    - name: 'Build project InMemoryQueue Server GRPC'
      run: dotnet build ${{ env.PROJECT_PATH_Server_GRPC }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Restore packages InMemoryQueue Server SignalR'
      run: dotnet restore ${{ env.PROJECT_PATH_Server_SignalR }}

    - name: 'Build project InMemoryQueue Server SignalR'
      run: dotnet build ${{ env.PROJECT_PATH_Server_SignalR }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Restore packages InMemoryQueue Client GRPC'
      run: dotnet restore ${{ env.PROJECT_PATH_Client_GRPC }}

    - name: 'Build project InMemoryQueue Client GRPC'
      run: dotnet build ${{ env.PROJECT_PATH_Client_GRPC }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Restore packages InMemoryQueue Client SignalR'
      run: dotnet restore ${{ env.PROJECT_PATH_Client_SignalR }}

    - name: 'Build project InMemoryQueue Client SignalR'
      run: dotnet build ${{ env.PROJECT_PATH_Client_SignalR }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Pack project InMemoryQueue Base'
      run: dotnet pack ${{ env.PROJECT_PATH_Base }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Pack project InMemoryQueue Server GRPC'
      run: dotnet pack ${{ env.PROJECT_PATH_Server_GRPC }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Pack project InMemoryQueue Server SignalR'
      run: dotnet pack ${{ env.PROJECT_PATH_Server_SignalR }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Pack project InMemoryQueue Client GRPC'
      run: dotnet pack ${{ env.PROJECT_PATH_Client_GRPC }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Pack project InMemoryQueue Client SignalR'
      run: dotnet pack ${{ env.PROJECT_PATH_Client_SignalR }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push packages'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.symbols.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}