name: "Deploy InMemoryQueue Base Package to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH_MemoryQueue: 'MemoryQueue.Base/MemoryQueue.Base.csproj'

  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 'Restore packages MemoryQueue'
      run: dotnet restore ${{ env.PROJECT_PATH_MemoryQueue }}

    - name: 'Build project MemoryQueue'
      run: dotnet build ${{ env.PROJECT_PATH_MemoryQueue }} --no-restore --configuration Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack project MemoryQueue'
      run: dotnet pack ${{ env.PROJECT_PATH_MemoryQueue }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push packages'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.symbols.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}